export const TOKEN = {
    FETCHED: "ACTION_TYPE_TOKEN_FETCHED",
    DELETED: "ACTION_TYPE_TOKEN_DELETED",
}

export const PRODUCT = {
    UPLOAD:{
        SUCCESS: "ACTION_TYPE_PRODUCT_UPLOAD_SUCCESS",
        ONGOING: "ACTION_TYPE_PRODUCT_UPLOAD__ONGOING",
        ERROR: "ACTION_TYPE_PRODUCT_UPLOAD__ERROR"
    },
    GET:{
        SUCCESS: "ACTION_TYPE_PRODUCT_GET_SUCCESS",
        ONGOING: "ACTION_TYPE_PRODUCT_GET__ONGOING",
        ERROR: "ACTION_TYPE_PRODUCT_GET__ERROR"
    },
    GETPIC:{
        SUCCESS: "ACTION_TYPE_PRODUCT_GETPIC_SUCCESS",
        ONGOING: "ACTION_TYPE_PRODUCT_GETPIC__ONGOING",
        ERROR: "ACTION_TYPE_PRODUCT_GETPIC__ERROR"
    }
    
}
